# Generated by Django 4.1.6 on 2023-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="totalBill",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="totalpayemnt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="lab",
            name="unique_id",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
    ]
