# Generated by Django 4.0.10 on 2023-03-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_reporttestinglist_reportlistcart_labcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlistcart',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='reportlistcart',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='reporttestinglist',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
