# Generated by Django 4.1 on 2023-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="report_status",
            field=models.CharField(
                choices=[("sample", "Sample Collected"), ("completed", "Completed"), ("delivered", "Delivered")],
                max_length=30,
            ),
        ),
    ]
