# Generated by Django 4.1 on 2023-02-07 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_lab_report_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reportlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("title", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="lab",
            name="title",
        ),
        migrations.AlterField(
            model_name="lab",
            name="date",
            field=models.DateField(default="2023-02-07"),
        ),
        migrations.AddField(
            model_name="lab",
            name="report_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportlist",
                verbose_name="Report Name",
            ),
        ),
    ]
