# Generated by Django 4.1.6 on 2023-03-01 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("pending confirmation", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("treated", "Treated"),
                            ("cancelled", "Cancelled"),
                            ("requested", "Requested"),
                        ],
                        default="pending confirmation",
                        max_length=40,
                    ),
                ),
                ("discount", models.IntegerField(blank=True, null=True)),
                (
                    "deposit_type",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("card", "Card")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=20, null=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "get_latest_by": ["date"],
            },
        ),
    ]
