# Generated by Django 4.1 on 2023-02-05 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("date", models.DateField()),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("pending confirmation", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("treated", "Treated"),
                            ("cancelled", "Cancelled"),
                            ("requested", "Requested"),
                        ],
                        default="pending confirmation",
                        max_length=40,
                    ),
                ),
                ("visti_description", models.TextField()),
                ("visit_charges", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount", models.IntegerField(blank=True, null=True)),
                ("grand_total", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "deposit_type",
                    models.CharField(
                        blank=True, choices=[("cash", "Cash"), ("card", "Card")], max_length=10, null=True
                    ),
                ),
                ("payment_status", models.CharField(choices=[("paid", "Paid"), ("unpaid", "Unpaid")], max_length=10)),
                ("remarks", models.CharField(blank=True, max_length=20, null=True)),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="patient.patient")),
            ],
            options={
                "get_latest_by": ["date"],
            },
        ),
    ]
