# Generated by Django 4.1 on 2023-02-07 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
