# Generated by Django 4.1.6 on 2023-03-01 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unique_id",
                    models.CharField(
                        blank=True, editable=False, max_length=40, null=True
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(max_length=11)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("others", "Others"),
                        ],
                        max_length=6,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a+", "A+"),
                            ("a-", "A-"),
                            ("b+", "B+"),
                            ("b-", "B-"),
                            ("ab+", "AB+"),
                            ("ab-", "AB-"),
                            ("o-", "O-"),
                            ("o+", "O-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("patient_age", models.IntegerField(null=True)),
                (
                    "grand_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0.00",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0.00",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "due",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default="0.00",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                (
                    "deposit_type",
                    models.CharField(
                        blank=True,
                        choices=[("cash", "Cash"), ("card", "Card")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("unpaid", "Unpaid"),
                            ("due", "Due"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
