# Generated by Django 4.1.6 on 2023-04-20 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Write Your Income Description.",
                        null=True,
                    ),
                ),
                ("sources", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.lab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Income",
                "verbose_name_plural": "Company Income",
            },
        ),
    ]
