# Generated by Django 4.1.6 on 2023-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_diagnosticincome_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosticincome",
            name="date",
        ),
        migrations.AlterField(
            model_name="diagnosticincome",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
