# Generated by Django 4.1 on 2023-02-05 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("unique_id", models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("designation", models.CharField(max_length=50)),
                ("commission", models.CharField(blank=True, default="0.00", max_length=4, null=True)),
                ("total", models.CharField(blank=True, default="0.00", max_length=4, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "depertment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="department.department"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("visit_charges", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("status", models.BooleanField(default=True)),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
