# Generated by Django 4.1.6 on 2023-03-01 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0001_initial"),
        ("department", "0001_initial"),
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofit",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="laboratory.lab"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofit",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="depertment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="department.department"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
